### DISCUSSION TITLE
Support full pull_request types

### DISCUSSION THREAD

**Discussion by votongchasqui** [Louis-7/ai-code-review#59] [Ideas]
Hi Louis-7,
I really love your action because it support more inputs to get expected GPT answers, and format of comment on pull request.
But I think your action only work with pull_request types: opened and synchronize.
I want to use your action with other pull_request types, ex: labeled.

Can you modify your action to support for all pull_request types?

Thank you very much!

**Comment by Louis-7** [comment]
Hi @votongchasqui, do you mean only trigger reviews when you label a pull request?

**Reply by Louis-7** [reply]
Suppose this is what you're asking. The timing to trigger GitHub Actions is controlled by yourself. You can read [Events that trigger workflows](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#label).

If you want to conditionally trigger one of your jobs in your action, you can read [Run Github Actions when pull requests have a specific label](https://stackoverflow.com/a/62331521/4436090).

In my repo, I'm calling the code review bot in the [.github/workflows/pr-code-review.yml](https://github.com/Louis-7/ai-code-review/blob/main/.github/workflows/pr-code-review.yml).

Let me know if this is the answer you're looking for.

**Reply by votongchasqui** [reply]
This is my workflow config
```
name: AI Code Reviewer

on:
  pull_request:
    types: [labeled]
    paths:
      - admin/app/**/*
      - admin/lib/**/*
      - app/**/*
      - lib/**/*
permissions: write-all
jobs:
  code-review:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'AI Review')      
    steps:
      - name: Remove AI Review label
        run: gh pr edit ${{ github.event.number }} --remove-label "AI Review"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
      - uses: actions/checkout@v4
      - name: AI Code Review
        uses: Louis-7/ai-code-review@v0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHAT_GPT_MODEL: ${{ vars.CHAT_GPT_MODEL }}
          PATH_TO_EXCLUDE: action/**/*, package-lock.json, package.json
          MAX_FILE_PER_PR: 20
          CUSTOMIZED_PROMPT: ${{ vars.CUSTOMIZED_REVIEW_CODE_PROMPT }}
```

I want to trigger your action when user assign label 'AI Review'.
But I see your action code only listen pull_request types opened and synchronize.
